apiVersion: v1
kind: Service
metadata:
  name: inker
  namespace: default
  labels:
    app: inker
spec:
  type: ClusterIP
  selector:
    app: inker
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
